### ISSUE TITLE
JQuery - использовать везде.

### ISSUE THREAD

**Issue by Geksanit** [AlexeyCheremnykh/task-4#10]
`const grid = document.querySelector('.js-game__grid');`
  `grid.style.width = '${cellsX * cellSize}px';`
  `grid.innerHTML = '';`

**Comment by chmnkh** [comment]
Исправил. Не ссылался на ишью в коммитах, потому что много чего переделывал/вообще выпиливал для #6. То же самое справедливо и для #9.
