### ISSUE TITLE
linebreak-style

### ISSUE THREAD

**Issue by Geksanit** [AlexeyCheremnykh/task-4#11]
В .eslintrc.json linebreak-style должен быть unix (он такой по умолчанию). Это стандарт индустрии, использование - LF. В вебшторме и вскоде есть возможность заменить разом все окончания строк.

**Comment by chmnkh** [comment]
Так если стандарт, то все таки везде делать, или только в .eslintrc.json?

**Comment by Geksanit** [comment]
да везде

**Comment by chmnkh** [comment]
А, ты имел в виду настройку eslnit'а, когда писал именно про .eslintrc.json.
Исправил.

**Comment by Geksanit** [comment]
Теперь настройки eslint правильные. А сами окончания строк в файлах какие ?

**Comment by chmnkh** [comment]
За счет настроек в .gitattributes (верхний коммит) теперь все eol символы в текстовых файлах в LF конвертиться будут.
Можешь попробовать git clone сделать например, я тестил, работает.
