### ISSUE TITLE
Добавить проверку прошлых поколений

### ISSUE THREAD

**Issue by Zarwlar** [AlexeyCheremnykh/task-4#13]

**Comment by Zarwlar** [comment]
Проверку состояния игры перенести в модель

**Comment by kinda-neat** [comment]
https://ru.wikipedia.org/wiki/%D0%98%D0%B3%D1%80%D0%B0_%C2%AB%D0%96%D0%B8%D0%B7%D0%BD%D1%8C%C2%BB
конфигурация на очередном шаге в точности (без сдвигов и поворотов) повторит себя же на одном из более ранних шагов (складывается периодическая конфигурация)
