### ISSUE TITLE
Операции по обрезанию матрицы

### ISSUE THREAD

**Issue by Zarwlar** [AlexeyCheremnykh/task-4#14]
Переписать мин и макс на метод(ы)
Переименовать переменные в методе обрезания (first -> top и т.д.)

**Comment by chmnkh** [comment]
Исправил

**Comment by Zarwlar** [comment]
В принципе, можно убрать функции, которые начинаются на calc, ведь туда даже ничего не передаётся? Ещё нужно убрать комментарий. Поскольку рассчёт соседей является одной из самых сложных (в плане чтения кода) частей задания, нужно добиться такой читаемости кода, чтобы комментарии были не нужны. Подзывай ребят, чтобы они, пробежавший взглядом, пытались определить, что делает та или иная строчка кода :)

**Comment by chmnkh** [comment]
Да я забыл, что мы пришли к тому, чтобы расчет первого столбца/строки и последнего столбца/строки в 2 метода вынести, т.к. там одни и те же расчеты, а отличается только переменная, которая в них участвует.

**Comment by chmnkh** [comment]
Поменял принцип расчета соседей.
Матрицу соседей вообще убрал. Все так же вычисляются соседние верхняя и нижняя стока, левый и правый столбец. С помощью lodash.range соответственно два массива получаются: со строками и со столбцами соседей, а также текущей клетки. Соответственно, если пройти редьюсом по двум этим массивам, то можно напрямую к "большой" матрице обращаться по нужным индексам, и если клетка живая, счетчик живых клеток увеличивать.
После этого проверяется, была ли текущая клетка живой, и если была, то количество живых соседей нужно на 1 уменьшить, потому что при их расчете текущая клетка тоже могла посчитаться.
