### ISSUE TITLE
Избавиться от .bind

### ISSUE THREAD

**Issue by Zarwlar** [AlexeyCheremnykh/task-4#16]
Использовать babel

**Comment by chmnkh** [comment]
Исправил

**Comment by kinda-neat** [comment]
Вот здесь убрать и можешь закрывать ишьюс :)
![2018-03-17 18-20-45](https://user-images.githubusercontent.com/27883524/37554778-07ec6028-2a10-11e8-8f9d-88ad167285d3.png)
