### ISSUE TITLE
Контроллер не должен знать про детали реализации вьюхи

### ISSUE THREAD

**Issue by Znack** [AlexeyCheremnykh/task-4#19]
Вот здесь лучше не писать, как конкретно происходят ивенты во вьюхе, контролер просто должен знать смысловые имена событий, например, что изменена ширина, а не что был блюр у инпута ширины. Потому что ширина может задавать не инпутом, и потому что срабатывать ивент может на каждое нажатие, а не только блюр. Лишнее зацепление, получается
```
    this._view.grid.cellUpdate.attach(this.updateMatrixCell);
    this._view.playButton.click.attach(this.toggleGameStatus);
    this._view.oneStepButton.click.attach(this.updateMatrix);
    this._view.newGameButton.click.attach(this.clearGrid);
    this._view.widthInput.blur.attach(this.changeMatrixWidth);
    this._view.heightInput.blur.attach(this.changeMatrixHeight);
    this._view.delayInput.blur.attach(this.changeDelay);
```

**Comment by Znack** [comment]
Ну и в целом лучше во вьюхе для всех вложенных элементов сделать методы явные, и может быть где-то более обобщенные, чтобы контроллер не знал об устройстве вьюхе

**Comment by chmnkh** [comment]
А можно сделать, чтобы те события компонент вьюхи, которые сейчас обзервит контроллер, обзервила бы сама вьюха, а потом бы уведомляла контроллер, но уже со смысловыми именами событий? Или перебор будет?

**Comment by chmnkh** [comment]
Так вроде довольно чисто получается, но как будто логика сложноватая.

**Comment by Znack** [comment]
Да, так как раз это и имел ввиду :)

По сложности это норм, наоборот у тебя сложность инкапсулирована во вьюхе остается и это упрощает в целом систему. Потому что так ты можешь схему систему нарисовать из трех квадратов, а в твоей текущей системе тебе по любому надо на общей схеме все квадратики вьюх рисовать, так как про них знает контроллер :)

**Comment by chmnkh** [comment]
Исправил

**Comment by Znack** [comment]
Контроллер прямо читать приятней стало :)

![image](https://user-images.githubusercontent.com/2928964/37840419-92c5fc70-2eef-11e8-860b-d869bfeefb33.png)

**Comment by Znack** [comment]
Теперь ты знаешь, что такое "Композиция" в ООП :) Это как раз у тебя вьюха такая получилась

Почитай статьи про Композицию и агрегирование по ООП пока, это очень полезная тема. И сравнение композиции и наследования, например (так как это очень для понимания реакта нужно будет)
