### ISSUE TITLE
game__wrong-input - пропущен префикс js-

### ISSUE THREAD

**Issue by Zarwlar** [AlexeyCheremnykh/task-4#4]

**Comment by Zarwlar** [comment]
И проверь в других местах ещё, на всякий случай

**Comment by chmnkh** [comment]
Так, ну во-первых я эту штуку сделал модификатором invalid (а не wrong, как в коммите случайно написал) для инпута. 
Вообще, там же в данном случае вешается/снимается класс, который за стили элемента отвечает, т.е. я же не буду для элемента стили через класс с js-префиксом задавать.
