### ISSUE TITLE
Перейти на arrow functions

### ISSUE THREAD

**Issue by Zarwlar** [AlexeyCheremnykh/task-4#5]

**Comment by chmnkh** [comment]
Можно пример? Вообще не понял, о чем речь, если честно. У меня НЕ стрелочных анонимных функций нигде нету вроде.

**Comment by Zarwlar** [comment]
```

    const updateCellAndListenMouseover = function updateCellAndSetMouseoverListener(event) {
      updateCell(event);
      $grid.bind('mouseover', updateCell);
      return false;
    };

    const unbindMouseover = function unbindMouseoverUpdateCellListener() {
      $grid.unbind('mouseover');
    };

```

**Comment by chmnkh** [comment]
Ты имеешь в виду сделать так? 
`const updateCellAndListenMouseover = (event) => {
      updateCell(event);
      $grid.bind('mouseover', updateCell);
      return false;
    };
`
А в каких случаях тогда так как по ссылке делать, и почему здесь не так?
https://github.com/airbnb/javascript#functions--declarations

**Comment by Geksanit** [comment]
Как по ссылке нужно делать когда не используешь стрелочные функции.

**Comment by chmnkh** [comment]
Не, это-то понятно, но как тогда определить, юзать стрелочные функции или нет? В airbnb стандартах явно пишут, юзать named function expression при объявлении функции, и даже пример плохого кода есть, который как бы намекает, что стрелочную функцию тут написать было бы плохо:
 ```
// bad
const foo = function () {
  // ...
};
```
А про стрелочные функции написано лишь то, что юзать их, если используется анонимная функция. Если следовать этим стандартам, то получается, всегда нужно named function expression юзать, если я где-то функцию объявляю. Поэтому почему здесь использовать таки стрелочные функции - не понятно. Какая-то путаница возникает, если честно.

**Comment by Zarwlar** [comment]
Вообще, [здесь](https://github.com/AlexeyCheremnykh/task-4/issues/5#issuecomment-371709502) не обязательно переходить на стрелочные, но твои имена функций выглядят не очень гармонично, в том плане, что они раскрывают реализацию, а не сообщает, что в целом делает функция. Названия в духе updateCellAndSetMouseoverListenerAndOpenDoorAndWalkTheDogAndETC могут помочь при просмотре error stack'a, но тем самым, ты раскрываешь содержимое тела функции — действия, которые она совершает. Короче говоря, не всегда просто понять специфику функции, название которой состоит из действий, которые она совершает
