### ISSUE TITLE
Всю работу с DOM вынести во View

### ISSUE THREAD

**Issue by Zarwlar** [AlexeyCheremnykh/task-4#6]

**Comment by chmnkh** [comment]
Исправил

**Comment by Zarwlar** [comment]
Внутри контроллера: 
`    const $grid = $('.js-game__grid');`
`    const delayInput = $('.js-game__delay-input')[0];`
`    const updatableCell = $('.js-game__grid-cell')[(cellRow * this._model.cellsX) + cellCol];`

**Comment by chmnkh** [comment]
Так это ж чтобы обработчики событий вешать.
Во всех примерах, которые кидали, и которые я сам находил, это именно в контроллере происходило.

**Comment by kinda-neat** [comment]
Такой подход с ростом проекта приводит контроллер в лапшу которая состоит из собственных обработчиков, обработчиков модели, вью, и так далее, тут больше вопрос про зону ответственности каждого слоя приложения, и очень важно ее понимать
Я тоже так в начале все сделал, делал все по примерам из инета, но в итоге так и не определил для себя ту самую зону ответственности, вот эта статья очень помогла, даже в риззоме есть заметка
https://rizzoma.com/topic/d5c429337bcaa70548fb5aeedee6d92b/0_b_8ndo_86lkk/
https://habrahabr.ru/post/321050/

**Comment by chmnkh** [comment]
Исправил.
Раздробил элементы View на классы Input, Grid, Button и ChangeableButton. При наступлении событий просто уведомляются наблюдатели, в данном случае контроллер. А дальше уже контроллер решает что делать: обновляет модель, таймер и так далее.
