### ISSUE TITLE
Убрать for из View

### ISSUE THREAD

**Issue by Zarwlar** [AlexeyCheremnykh/task-4#8]

**Comment by chmnkh** [comment]
Один for убрал (он вообще ненужный был), второй оставил, ибо там не итерация по чему-то, а просто N раз нужно что-то сделать.

**Comment by Zarwlar** [comment]
const N = 10; 
[...Array(N).keys()].forEach
Или какой-нибудь range из lodash

**Comment by chmnkh** [comment]
Исправил
