### ISSUE TITLE
Переменные JQuery

### ISSUE THREAD

**Issue by Geksanit** [AlexeyCheremnykh/task-4#9]
`const aliveCells = $('.js-game__grid-cell.game__grid-cell_alive');`
Все переменные, которые поддерживают jQuery API, должны начинаться со знака $

**Comment by Geksanit** [comment]
Это из стандартов.

**Comment by chmnkh** [comment]
Исправил. Не ссылался на ишью в коммитах, потому что много чего переделывал/вообще выпиливал для #6. То же самое справедливо и для #10.
